# Homebrew formula for bench-harness — portable harness-side assets that
# every BenchAGI openclaw machine pulls to stay in sync.
#
# Install (end-user):
#   brew tap benchagi/tap
#   brew install benchagi/tap/bench-harness
#   brew services start bench-harness
#
# Replaces the 60-line shell-by-shell onboarding runbook with one command.
#
# PREREQUISITE: this formula's `url` resolves to a GitHub release tarball
# of BenchAGI/bench-harness at tag v0.1.0. That tag does not exist yet —
# cut a release before publishing this formula. The repo is private, so
# `brew install` will require an authenticated download (HOMEBREW_GITHUB_API_TOKEN
# or equivalent) until/unless bench-harness is made public.
class BenchHarness < Formula
  desc "Launch-readiness, vault-sync, and canvas-drift harness for BenchAGI hosts"
  homepage "https://github.com/BenchAGI/bench-harness"
  url "https://github.com/BenchAGI/bench-harness/archive/refs/tags/v0.1.0.tar.gz"
  # sha256 will be filled in once v0.1.0 is tagged. Compute with:
  #   curl -L https://github.com/BenchAGI/bench-harness/archive/refs/tags/v0.1.0.tar.gz | shasum -a 256
  version "0.1.0"
  sha256 "0000000000000000000000000000000000000000000000000000000000000000"
  license "MIT"

  depends_on "bash"
  depends_on "gh"
  depends_on "git"
  depends_on "jq"

  def install
    libexec.install "scripts"
    libexec.install "launchd" if Dir.exist?("launchd")
    libexec.install "bootstrap.sh", "sync.sh"

    # Symlink user-facing scripts into bin/ with a "bench-" prefix to avoid
    # polluting PATH with generic names like `vault-sync.sh`.
    {
      "launch-readiness.sh"          => "bench-launch-readiness",
      "vault-sync.sh"                => "bench-vault-sync",
      "canvas-drift-detector.sh"     => "bench-canvas-drift",
      "canvas-edge-flow-detector.sh" => "bench-canvas-edge-flow",
      "audit-worktrees.sh"           => "bench-audit-worktrees",
      "backup-vault-to-colludr.sh"   => "bench-vault-backup",
      "test-restore-from-colludr.sh" => "bench-vault-restore-test",
    }.each do |src, dst|
      target = libexec/"scripts"/src
      bin.install_symlink target => dst if target.exist?
    end

    # Generate a TCC-safe wrapper that resolves LR_MONO_REPO at runtime
    # instead of relying on a per-host plist override. launchd-spawned `git`
    # cannot read inside ~/Documents/ (TCC), so we cascade candidates and
    # pick the first one where `git rev-parse --git-dir` succeeds.
    (libexec/"bin").mkpath
    (libexec/"bin/launch-readiness-wrapper").write <<~SH
      #!/bin/bash
      # Auto-generated by the bench-harness Homebrew formula. Do not edit.
      # Resolves LR_MONO_REPO with a TCC-aware cascade and then execs
      # launch-readiness.sh. See docs/architecture/macos-tcc-launchd-git
      # in BenchAGI_Mono_Repo for the full rationale.
      set -uo pipefail

      if [ -z "${LR_MONO_REPO:-}" ]; then
        for candidate in \\
          "$HOME/Documents/BenchAGI_Mono_Repo" \\
          "$HOME/clawd/kestrel-crew/BenchAGI_Mono_Repo" \\
          "$HOME/code/BenchAGI_Mono_Repo"; do
          if [ -d "$candidate" ] && \\
             ( cd "$candidate" && git rev-parse --git-dir >/dev/null 2>&1 ); then
            export LR_MONO_REPO="$candidate"
            break
          fi
        done
      fi

      exec "#{libexec}/scripts/launch-readiness.sh" "$@"
    SH
    chmod 0755, libexec/"bin/launch-readiness-wrapper"
    bin.install_symlink libexec/"bin/launch-readiness-wrapper" => "bench-launch-readiness-tcc"
  end

  service do
    run [opt_bin/"bench-launch-readiness-tcc"]
    keep_alive false
    run_at_load true
    interval 1800
    log_path "#{Dir.home}/.openclaw/logs/launch-readiness.out.log"
    error_log_path "#{Dir.home}/.openclaw/logs/launch-readiness.err.log"
  end

  def caveats
    <<~EOS
      bench-harness is installed. Scripts live in:
        #{opt_libexec}/scripts/

      User-facing commands on PATH:
        bench-launch-readiness        # full readiness run
        bench-launch-readiness-tcc    # same, with TCC-safe LR_MONO_REPO cascade
        bench-vault-sync              # auto commit/rebase/push of the wiki vault
        bench-canvas-drift            # canvas truth detector
        bench-vault-backup            # local snapshot to colludr
        bench-audit-worktrees         # git worktree hygiene

      Required one-time setup:
        1. Set BENCH_WIKI_INGEST_KEY (read from 1Password):
             export BENCH_WIKI_INGEST_KEY="$(op read 'op://BenchAGI/wiki-ingest/key')"
           Persist it (zsh):
             echo 'export BENCH_WIKI_INGEST_KEY="$(op read op://BenchAGI/wiki-ingest/key)"' >> ~/.zshrc
        2. Clone the mono repo somewhere the launchd-spawned git can read.
           TCC-safe locations the wrapper auto-detects (in order):
             ~/Documents/BenchAGI_Mono_Repo       (works for interactive shells)
             ~/clawd/kestrel-crew/BenchAGI_Mono_Repo  (TCC-safe; preferred for launchd)
             ~/code/BenchAGI_Mono_Repo
           If none of those exist, set LR_MONO_REPO explicitly.
        3. Start the launchd agent (runs every 30 minutes):
             brew services start bench-harness
           Or run on demand:
             bench-launch-readiness --dry-run

      Logs:
        ~/.openclaw/logs/launch-readiness.log
        ~/.openclaw/logs/launch-readiness.err.log
        ~/.openclaw/logs/vault-sync.log

      Upgrading: brew upgrade benchagi/tap/bench-harness && brew services restart bench-harness
    EOS
  end

  test do
    # Dry-run must exit 0 even on a host with no mono repo or wiki present:
    # the script's own --dry-run branch skips writes and tolerates missing state.
    # We pass --no-fetch so the test never tries to hit the network.
    output = shell_output("#{bin}/bench-launch-readiness --dry-run --no-fetch 2>&1")
    assert_match(/launch-readiness|check|green|red/i, output)
  end
end
